CREATE TABLE customers (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  dob DATE NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE orders (
  OrderID INT NOT NULL AUTO_INCREMENT,
  Customer VARCHAR(255) NOT NULL,
  DateOfOrder DATE NOT NULL,
  ListOfItems VARCHAR(1000) NOT NULL,
  TotalPrice DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (OrderID)
);
CREATE TABLE chairs (
  ChairID INT NOT NULL AUTO_INCREMENT,
  ChairDimensions VARCHAR(255) NOT NULL,
  MaterialType VARCHAR(255) NOT NULL,
  Color VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ChairID)
);
CREATE TABLE sofas (
  SofaID INT NOT NULL AUTO_INCREMENT,
  SofaDimensions VARCHAR(255) NOT NULL,
  MaterialType VARCHAR(255) NOT NULL,
  Color VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (SofaID)
);
CREATE TABLE dining_tables (
  DiningTableID INT NOT NULL AUTO_INCREMENT,
  TableDimensions VARCHAR(255) NOT NULL,
  MaterialType VARCHAR(255) NOT NULL,
  Color VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  ListOfChairs INT NOT NULL,
  PRIMARY KEY (DiningTableID)
);
CREATE TABLE beds (
  BedID INT NOT NULL AUTO_INCREMENT,
  BedDimensions VARCHAR(255) NOT NULL,
  MaterialType VARCHAR(255) NOT NULL,
  Color VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (BedID)
);
CREATE TABLE cabinets (
  CabinetID INT NOT NULL AUTO_INCREMENT,
  CabinetDimensions VARCHAR(255) NOT NULL,
  MaterialType VARCHAR(255) NOT NULL,
  Color VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  NumberOfDrawers INT NOT NULL,
  PRIMARY KEY (CabinetID)
);
